apiVersion: v1
kind: Service
metadata:
  name: resilience-demo-svc
  namespace: chaos-demo
  labels:
    app: resilience-demo
spec:
  type: ClusterIP
  selector:
    app: resilience-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
